version: '3'
services:

  django:
    build:
      context: .
    depends_on:
      - redis
    env_file:
      - .env.prod
    ports:
      - "8001:8001"
    command: ["gunicorn", "perfil.wsgi:application", "--reload", "--bind", "0.0.0.0:8001", "--workers", "1", "--log-level", "INFO", "--timeout", "300"]

  redis:
    image: redis:4.0.11-alpine
