version: '3'
services:

  django:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./perfil:/code/perfil
      - ./data:/mnt/data

  jupyter:
    build:
      context: jupyter
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/code
      - ./data:/mnt/data

  postgres:
    image: postgres:10.5-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./data:/mnt/data
    environment:
      - POSTGRES_DB=perfilpolitico
      - POSTGRES_USER=perfilpolitico
      - POSTGRES_PASSWORD=perfilpolitico
    ports:
      - 5432:5432

  redis:
    image: redis:4.0.11-alpine
